procedure SetupResource(const AName, ASuffix: string);
begin
  FindResource(AName).Set('ID', AName + '.' + ASuffix);
end;

procedure SetupTheme(const ASuffix: string);
begin
  SetupResource('Skin.Color.Border', ASuffix);
  SetupResource('Skin.Color.Content.Background', ASuffix);
  SetupResource('Skin.Color.Content.Text', ASuffix);
  SetupResource('Skin.Color.Content.Text.Disabled', ASuffix);
  SetupResource('Skin.Color.ControlPanel.Background', ASuffix);
  SetupResource('Skin.Color.BottomPanel.Background', ASuffix);
  SetupResource('Skin.Color.EditBox.Background', ASuffix);
  SetupResource('Skin.Color.Tabs.Background', ASuffix);
  SetupResource('Skin.Color.Item.Normal2', ASuffix);
  SetupResource('Skin.Color.Item.Selected', ASuffix);
  SetupResource('Skin.Color.Item.SelectedInactive', ASuffix);
  SetupResource('Skin.Color.Item.SelectedText', ASuffix);
  SetupResource('Skin.Color.Item.SelectedTextInactive', ASuffix);
  SetupResource('Skin.Color.Item.PlayingSelected', ASuffix);
  SetupResource('Skin.Color.Item.PlayingSelectedInactive', ASuffix);
  SetupResource('Skin.Color.GroupDetails.Background', ASuffix);                 
  SetupResource('Skin.Color.GroupDetails.Text', ASuffix);
  SetupResource('Skin.Color.SeekBar', ASuffix);

  SetupResource('Skin.Fonts.GroupDetails', ASuffix);
  SetupResource('Skin.Fonts.Column', ASuffix);
  SetupResource('Skin.Fonts.Header.Normal', ASuffix);
  SetupResource('Skin.Fonts.Header.Selected', ASuffix);
  SetupResource('Skin.Fonts.Item.Dead', ASuffix);
  SetupResource('Skin.Fonts.Item.DeadSelectedInactive', ASuffix);
  SetupResource('Skin.Fonts.Item.Normal', ASuffix);
  SetupResource('Skin.Fonts.Item.Playing', ASuffix);
  SetupResource('Skin.Fonts.Item.Selected', ASuffix);
  SetupResource('Skin.Fonts.Item.Normal2', ASuffix);
  SetupResource('Skin.Fonts.Item.Selected2', ASuffix);  
  SetupResource('Skin.Fonts.GroupingPresets.Title', ASuffix);
  SetupResource('Skin.Fonts.Tabs.Active', ASuffix);
  SetupResource('Skin.Fonts.Tabs.ActiveHot', ASuffix);
  SetupResource('Skin.Fonts.Tabs.Hot', ASuffix);
  SetupResource('Skin.Fonts.Tabs.Normal', ASuffix);
  SetupResource('Skin.Fonts.Tabs.Playing', ASuffix);
  SetupResource('Skin.Fonts.Tabs.PlayingActive', ASuffix);
  SetupResource('Skin.Fonts.Tabs.PlayingActiveHot', ASuffix);
  SetupResource('Skin.Fonts.Tabs.PlayingHot', ASuffix);

  SetupResource('Skin.TextureEx.Item.CheckBox', ASuffix);
  SetupResource('Skin.TextureEx.Header', ASuffix);
  SetupResource('Skin.TextureEx.Header.CheckBox', ASuffix);
  SetupResource('Skin.TextureEx.Header.Expand', ASuffix);
  SetupResource('Skin.TextureEx.Tabs.Next', ASuffix);
  SetupResource('Skin.TextureEx.Tabs.Prev', ASuffix);
  SetupResource('Skin.TextureEx.Tabs.TabHeader', ASuffix);
  SetupResource('Skin.TextureEx.ScrollBar.ThumbHorz', ASuffix);
  SetupResource('Skin.TextureEx.ScrollBar.ThumbVert', ASuffix);
  SetupResource('Skin.TextureEx.EditBox.Clear', ASuffix);
  SetupResource('Skin.TextureEx.Layout.Splitter', ASuffix);
  SetupResource('Skin.TextureEx.Button.GroupingPresets', ASuffix);
  SetupResource('Skin.TextureEx.AlphabeticIndex.Scroller', ASuffix);
  SetupResource('Skin.TextureEx.Button', ASuffix);      
  SetupResource('Skin.TextureEx.CheckBox', ASuffix); 
  SetupResource('Skin.TextureEx.Column', ASuffix); 
  SetupResource('Skin.TextureEx.GroupingTree.NodeImages', ASuffix);
  SetupResource('Skin.Color.LeftPanel.Background', ASuffix);
  SetupResource('Skin.TextureEx.Window.Shadow', ASuffix);
  SetupResource('Skin.Fonts.Track.NewPlan', ASuffix);
  SetupResource('Skin.TextureEx.Button.MusicLibrary', ASuffix);
  SetupResource('Skin.TextureEx.Button.Playlist', ASuffix);
  SetupResource('Skin.Texture.MenuBackground', ASuffix);
  SetupResource('Skin.Texture.MenuGutter', ASuffix);
  SetupResource('Skin.TextureEx.Button.NowPlaying', ASuffix);
  SetupResource('Skin.TextureEx.PlayPause', ASuffix);
  SetupResource('Skin.TextureEx.SkinThumb', ASuffix);
  SetupResource('Skin.TextureEx.Window.Shadow.Half', ASuffix);
  SetupResource('Skin.TextureEx.CoverContent', ASuffix);
  SetupResource('Skin.TextureEx.Background.Half', ASuffix);
  SetupResource('Skin.TextureEx.Background.Content', ASuffix);
  SetupResource('Skin.TextureEx.GradientMainPlayAction', ASuffix); 
  SetupResource('Skin.Fonts.Track.NewPlan.ca3rd.TrackInfo', ASuffix);
  SetupResource('Skin.TextureEx.Slide.Up', ASuffix); 
  SetupResource('Skin.TextureEx.Window.Shadow.Rounded', ASuffix); 
  SetupResource('Skin.TextureEx.Window.Shadow.Rounded.Top', ASuffix); 
  SetupResource('Skin.TextureEx.Window.Shadow.Rounded.Bottom', ASuffix);
  SetupResource('Skin.TextureEx.Window.Shadow.Rounded.Bottom.2nd', ASuffix);
  SetupResource('Skin.TextureEx.Window.Shadow.Content', ASuffix); 
  SetupResource('Skin.TextureEx.Slide.Top', ASuffix);
  SetupResource('Skin.TextureEx.Volume.Top', ASuffix);
  SetupResource('Skin.TextureEx.Button.Character', ASuffix);
  SetupResource('Skin.TextureEx.EnableDisable', ASuffix); 
  SetupResource('Skin.Font.New.Title', ASuffix);
  SetupResource('Skin.TextureEx.Settings.Button', ASuffix);
  SetupResource('Skin.TextureEx.NewVolume', ASuffix);
  SetupResource('Skin.TextureEx.NowPlay.Chara.Button', ASuffix);
  SetupResource('Skin.TextureEx.NowPlay.TrackInfo', ASuffix);
  
  SetupResource('Skin.Button.Action', ASuffix);
  SetupResource('Skin.TextureEx.Bg.Setting', ASuffix);
  SetupResource('Skin.TextureEx.Bg.SettingInfo', ASuffix);  
  SetupResource('Skin.TextureEx.Bg.SettingAction', ASuffix);
  SetupResource('Skin.TextureEx.Slider.Horizontal', ASuffix);
  SetupResource('Skin.TextureEx.Slider.Thumb', ASuffix);
end;

procedure Execute(var State: Integer);
begin
  BeginUpdateResources;
  case State of
    0: SetupTheme('Light');
    1: SetupTheme('Dark');      
  end;
  EndUpdateResources;
end;
